//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docutain_SDK_Example_.NET_MAUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Docutain_SDK_Example_.NET_MAUI.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount_hint {
            get {
                return ResourceManager.GetString("amount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC.
        /// </summary>
        internal static string BIC_hint {
            get {
                return ResourceManager.GetString("BIC_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city_hint {
            get {
                return ResourceManager.GetString("city_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string customerId_hint {
            get {
                return ResourceManager.GetString("customerId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Extraction.
        /// </summary>
        internal static string data_extraction {
            get {
                return ResourceManager.GetString("data extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract data, e.g. invoice data, from a previously scanned or imported (PDF or Image) document..
        /// </summary>
        internal static string dataExtractDesc {
            get {
                return ResourceManager.GetString("dataExtractDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date_hint {
            get {
                return ResourceManager.GetString("date_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the document scanner which provides automatic scanning of paper documents..
        /// </summary>
        internal static string docScannerDesc {
            get {
                return ResourceManager.GetString("docScannerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Scanner.
        /// </summary>
        internal static string document_scanner {
            get {
                return ResourceManager.GetString("document scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF Document.
        /// </summary>
        internal static string generate_pdf {
            get {
                return ResourceManager.GetString("generate pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a searchable (includes recognized text) PDF document out of the scanned pages or imported image..
        /// </summary>
        internal static string generatePDFDesc {
            get {
                return ResourceManager.GetString("generatePDFDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        internal static string IBAN_hint {
            get {
                return ResourceManager.GetString("IBAN_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Import.
        /// </summary>
        internal static string input_option_image {
            get {
                return ResourceManager.GetString("input_option_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Import.
        /// </summary>
        internal static string input_option_PDF {
            get {
                return ResourceManager.GetString("input_option_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Scan.
        /// </summary>
        internal static string input_option_scan {
            get {
                return ResourceManager.GetString("input_option_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice ID.
        /// </summary>
        internal static string invoiceId_hint {
            get {
                return ResourceManager.GetString("invoiceId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 1.
        /// </summary>
        internal static string name1_hint {
            get {
                return ResourceManager.GetString("name1_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 1.
        /// </summary>
        internal static string name2_hint {
            get {
                return ResourceManager.GetString("name2_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 1.
        /// </summary>
        internal static string name3_hint {
            get {
                return ResourceManager.GetString("name3_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PDF.
        /// </summary>
        internal static string open_pdf {
            get {
                return ResourceManager.GetString("open_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment State.
        /// </summary>
        internal static string paymentState_hint {
            get {
                return ResourceManager.GetString("paymentState_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone_hint {
            get {
                return ResourceManager.GetString("phone_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string reference_hint {
            get {
                return ResourceManager.GetString("reference_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street_hint {
            get {
                return ResourceManager.GetString("street_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Recognition (OCR).
        /// </summary>
        internal static string text_recognition {
            get {
                return ResourceManager.GetString("text recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run OCR on the previously scanned or imported (PDF or Image) document and get the recognized text..
        /// </summary>
        internal static string textRecognitionDesc {
            get {
                return ResourceManager.GetString("textRecognitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, scan or import a document.
        /// </summary>
        internal static string title_import_option {
            get {
                return ResourceManager.GetString("title_import_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        internal static string zipcode_hint {
            get {
                return ResourceManager.GetString("zipcode_hint", resourceCulture);
            }
        }
    }
}
