//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docutain_SDK_Example_.NET_MAUI {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Docutain_SDK_Example_.NET_MAUI.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AllowCaptureModeSetting ähnelt.
        /// </summary>
        internal static string AllowCaptureModeSetting {
            get {
                return ResourceManager.GetString("AllowCaptureModeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If true, the document scanner toolbar will display an item that allows the user to switch between automatic and manual camera triggering. ähnelt.
        /// </summary>
        internal static string AllowCaptureModeSetting_Description {
            get {
                return ResourceManager.GetString("AllowCaptureModeSetting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AllowPageArrangement ähnelt.
        /// </summary>
        internal static string AllowPageArrangement {
            get {
                return ResourceManager.GetString("AllowPageArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If false, the bottom toolbar will hide the arrange page item. ähnelt.
        /// </summary>
        internal static string AllowPageArrangement_Description {
            get {
                return ResourceManager.GetString("AllowPageArrangement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AllowPageCropping ähnelt.
        /// </summary>
        internal static string AllowPageCropping {
            get {
                return ResourceManager.GetString("AllowPageCropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If false, the bottom toolbar will hide the page cropping item. ähnelt.
        /// </summary>
        internal static string AllowPageCropping_Description {
            get {
                return ResourceManager.GetString("AllowPageCropping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AllowPageFilter ähnelt.
        /// </summary>
        internal static string AllowPageFilter {
            get {
                return ResourceManager.GetString("AllowPageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If false, the bottom toolbar will hide the filter page item. ähnelt.
        /// </summary>
        internal static string AllowPageFilter_Description {
            get {
                return ResourceManager.GetString("AllowPageFilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AllowPageRotation ähnelt.
        /// </summary>
        internal static string AllowPageRotation {
            get {
                return ResourceManager.GetString("AllowPageRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If false, the bottom toolbar will hide the rotate page item. ähnelt.
        /// </summary>
        internal static string AllowPageRotation_Description {
            get {
                return ResourceManager.GetString("AllowPageRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        internal static string amount_hint {
            get {
                return ResourceManager.GetString("amount_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        internal static string amount_hint1 {
            get {
                return ResourceManager.GetString("amount_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoCapture ähnelt.
        /// </summary>
        internal static string AutoCapture {
            get {
                return ResourceManager.GetString("AutoCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If true, the camera will capture the image automatically at the right moment. ähnelt.
        /// </summary>
        internal static string AutoCapture_Description {
            get {
                return ResourceManager.GetString("AutoCapture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoCrop ähnelt.
        /// </summary>
        internal static string AutoCrop {
            get {
                return ResourceManager.GetString("AutoCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If true, image gets automatically cropped if document was detected. This applies only when importing images. ähnelt.
        /// </summary>
        internal static string AutoCrop_Description {
            get {
                return ResourceManager.GetString("AutoCrop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic capture ähnelt.
        /// </summary>
        internal static string automaticCapture {
            get {
                return ResourceManager.GetString("automaticCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIC ähnelt.
        /// </summary>
        internal static string BIC_hint {
            get {
                return ResourceManager.GetString("BIC_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIC ähnelt.
        /// </summary>
        internal static string BIC_hint1 {
            get {
                return ResourceManager.GetString("BIC_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom bar background ähnelt.
        /// </summary>
        internal static string bottomBarBackground {
            get {
                return ResourceManager.GetString("bottomBarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom bar foreground ähnelt.
        /// </summary>
        internal static string bottomBarForeground {
            get {
                return ResourceManager.GetString("bottomBarForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City ähnelt.
        /// </summary>
        internal static string city_hint {
            get {
                return ResourceManager.GetString("city_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City ähnelt.
        /// </summary>
        internal static string city_hint1 {
            get {
                return ResourceManager.GetString("city_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorBottomBarBackground ähnelt.
        /// </summary>
        internal static string ColorBottomBarBackground {
            get {
                return ResourceManager.GetString("ColorBottomBarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint the bottom toolbar background of the image editing page. ähnelt.
        /// </summary>
        internal static string ColorBottomBarBackground_Description {
            get {
                return ResourceManager.GetString("ColorBottomBarBackground_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorBottomBarForeground ähnelt.
        /// </summary>
        internal static string ColorBottomBarForeground {
            get {
                return ResourceManager.GetString("ColorBottomBarForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint the buttons within the bottom toolbar of the image editing page. ähnelt.
        /// </summary>
        internal static string ColorBottomBarForeground_Description {
            get {
                return ResourceManager.GetString("ColorBottomBarForeground_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorOnSecondary ähnelt.
        /// </summary>
        internal static string ColorOnSecondary {
            get {
                return ResourceManager.GetString("ColorOnSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint elements that reside on ColorSecondary, like the icon of the capture button. ähnelt.
        /// </summary>
        internal static string ColorOnSecondary_Description {
            get {
                return ResourceManager.GetString("ColorOnSecondary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorPrimary ähnelt.
        /// </summary>
        internal static string ColorPrimary {
            get {
                return ResourceManager.GetString("ColorPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint progress indicators and dialog buttons. ähnelt.
        /// </summary>
        internal static string ColorPrimary_Description {
            get {
                return ResourceManager.GetString("ColorPrimary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorScanButtonsForeground ähnelt.
        /// </summary>
        internal static string ColorScanButtonsForeground {
            get {
                return ResourceManager.GetString("ColorScanButtonsForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint the foreground of the buttons of the scan layout, like the torch button. ähnelt.
        /// </summary>
        internal static string ColorScanButtonsForeground_Description {
            get {
                return ResourceManager.GetString("ColorScanButtonsForeground_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorScanButtonsLayoutBackground ähnelt.
        /// </summary>
        internal static string ColorScanButtonsLayoutBackground {
            get {
                return ResourceManager.GetString("ColorScanButtonsLayoutBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint the background of the layout containing the buttons of the scan layout, like the capture button or torch button. ähnelt.
        /// </summary>
        internal static string ColorScanButtonsLayoutBackground_Description {
            get {
                return ResourceManager.GetString("ColorScanButtonsLayoutBackground_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorScanPolygon ähnelt.
        /// </summary>
        internal static string ColorScanPolygon {
            get {
                return ResourceManager.GetString("ColorScanPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint the polygon overlay which highlights the currently detected document. ähnelt.
        /// </summary>
        internal static string ColorScanPolygon_Description {
            get {
                return ResourceManager.GetString("ColorScanPolygon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorSecondary ähnelt.
        /// </summary>
        internal static string ColorSecondary {
            get {
                return ResourceManager.GetString("ColorSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint selectable controls and the capture button. ähnelt.
        /// </summary>
        internal static string ColorSecondary_Description {
            get {
                return ResourceManager.GetString("ColorSecondary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color settings ähnelt.
        /// </summary>
        internal static string colorSettings {
            get {
                return ResourceManager.GetString("colorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorTopBarBackground ähnelt.
        /// </summary>
        internal static string ColorTopBarBackground {
            get {
                return ResourceManager.GetString("ColorTopBarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint the top toolbar background. ähnelt.
        /// </summary>
        internal static string ColorTopBarBackground_Description {
            get {
                return ResourceManager.GetString("ColorTopBarBackground_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ColorTopBarForeground ähnelt.
        /// </summary>
        internal static string ColorTopBarForeground {
            get {
                return ResourceManager.GetString("ColorTopBarForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used to tint the elements contained in the top toolbar, like buttons and titles. ähnelt.
        /// </summary>
        internal static string ColorTopBarForeground_Description {
            get {
                return ResourceManager.GetString("ColorTopBarForeground_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop imported images ähnelt.
        /// </summary>
        internal static string cropImportedImages {
            get {
                return ResourceManager.GetString("cropImportedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer ID ähnelt.
        /// </summary>
        internal static string customerId_hint {
            get {
                return ResourceManager.GetString("customerId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer ID ähnelt.
        /// </summary>
        internal static string customerId_hint1 {
            get {
                return ResourceManager.GetString("customerId_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Extraction ähnelt.
        /// </summary>
        internal static string data_extraction {
            get {
                return ResourceManager.GetString("data extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Extraction ähnelt.
        /// </summary>
        internal static string data_extraction1 {
            get {
                return ResourceManager.GetString("data extraction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extract data, e.g. invoice data, from a previously scanned or imported (PDF or Image) document. ähnelt.
        /// </summary>
        internal static string dataExtractDesc {
            get {
                return ResourceManager.GetString("dataExtractDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extract data, e.g. invoice data, from a previously scanned or imported (PDF or Image) document. ähnelt.
        /// </summary>
        internal static string dataExtractDesc1 {
            get {
                return ResourceManager.GetString("dataExtractDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string date_hint {
            get {
                return ResourceManager.GetString("date_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string date_hint1 {
            get {
                return ResourceManager.GetString("date_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DefaultScanFilter ähnelt.
        /// </summary>
        internal static string DefaultScanFilter {
            get {
                return ResourceManager.GetString("DefaultScanFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The default scan filter that will be used after scan. ähnelt.
        /// </summary>
        internal static string DefaultScanFilter_Description {
            get {
                return ResourceManager.GetString("DefaultScanFilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starts the document scanner which provides automatic scanning of paper documents. ähnelt.
        /// </summary>
        internal static string docScannerDesc {
            get {
                return ResourceManager.GetString("docScannerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starts the document scanner which provides automatic scanning of paper documents. ähnelt.
        /// </summary>
        internal static string docScannerDesc1 {
            get {
                return ResourceManager.GetString("docScannerDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Scanner ähnelt.
        /// </summary>
        internal static string document_scanner {
            get {
                return ResourceManager.GetString("document scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Scanner ähnelt.
        /// </summary>
        internal static string document_scanner1 {
            get {
                return ResourceManager.GetString("document scanner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit settings ähnelt.
        /// </summary>
        internal static string editSettings {
            get {
                return ResourceManager.GetString("editSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate PDF Document ähnelt.
        /// </summary>
        internal static string generate_pdf {
            get {
                return ResourceManager.GetString("generate pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate PDF Document ähnelt.
        /// </summary>
        internal static string generate_pdf1 {
            get {
                return ResourceManager.GetString("generate pdf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate a searchable (includes recognized text) PDF document out of the scanned pages or imported image. ähnelt.
        /// </summary>
        internal static string generatePDFDesc {
            get {
                return ResourceManager.GetString("generatePDFDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate a searchable (includes recognized text) PDF document out of the scanned pages or imported image. ähnelt.
        /// </summary>
        internal static string generatePDFDesc1 {
            get {
                return ResourceManager.GetString("generatePDFDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IBAN ähnelt.
        /// </summary>
        internal static string IBAN_hint {
            get {
                return ResourceManager.GetString("IBAN_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IBAN ähnelt.
        /// </summary>
        internal static string IBAN_hint1 {
            get {
                return ResourceManager.GetString("IBAN_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Scan Gallery ähnelt.
        /// </summary>
        internal static string input_option_gallery {
            get {
                return ResourceManager.GetString("input_option_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Import ähnelt.
        /// </summary>
        internal static string input_option_image {
            get {
                return ResourceManager.GetString("input_option_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Import ähnelt.
        /// </summary>
        internal static string input_option_image1 {
            get {
                return ResourceManager.GetString("input_option_image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Import ähnelt.
        /// </summary>
        internal static string input_option_PDF {
            get {
                return ResourceManager.GetString("input_option_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Import ähnelt.
        /// </summary>
        internal static string input_option_PDF1 {
            get {
                return ResourceManager.GetString("input_option_PDF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Scan Camera ähnelt.
        /// </summary>
        internal static string input_option_scan {
            get {
                return ResourceManager.GetString("input_option_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Scan ähnelt.
        /// </summary>
        internal static string input_option_scan1 {
            get {
                return ResourceManager.GetString("input_option_scan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice ID ähnelt.
        /// </summary>
        internal static string invoiceId_hint {
            get {
                return ResourceManager.GetString("invoiceId_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice ID ähnelt.
        /// </summary>
        internal static string invoiceId_hint1 {
            get {
                return ResourceManager.GetString("invoiceId_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MultiPage ähnelt.
        /// </summary>
        internal static string MultiPage {
            get {
                return ResourceManager.GetString("MultiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If true, scanning multi page documents is possible. Set this to false if you need to scan single page documents. ähnelt.
        /// </summary>
        internal static string MultiPage_Description {
            get {
                return ResourceManager.GetString("MultiPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name 1 ähnelt.
        /// </summary>
        internal static string name1_hint {
            get {
                return ResourceManager.GetString("name1_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name 1 ähnelt.
        /// </summary>
        internal static string name1_hint1 {
            get {
                return ResourceManager.GetString("name1_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name 1 ähnelt.
        /// </summary>
        internal static string name2_hint {
            get {
                return ResourceManager.GetString("name2_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name 1 ähnelt.
        /// </summary>
        internal static string name2_hint1 {
            get {
                return ResourceManager.GetString("name2_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name 1 ähnelt.
        /// </summary>
        internal static string name3_hint {
            get {
                return ResourceManager.GetString("name3_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name 1 ähnelt.
        /// </summary>
        internal static string name3_hint1 {
            get {
                return ResourceManager.GetString("name3_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On Secondary ähnelt.
        /// </summary>
        internal static string onSecondary {
            get {
                return ResourceManager.GetString("onSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open PDF ähnelt.
        /// </summary>
        internal static string open_pdf {
            get {
                return ResourceManager.GetString("open_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PageArrangementShowDeleteButton ähnelt.
        /// </summary>
        internal static string PageArrangementShowDeleteButton {
            get {
                return ResourceManager.GetString("PageArrangementShowDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If true, each item of the page arrangement functionality will show a delete button. ähnelt.
        /// </summary>
        internal static string PageArrangementShowDeleteButton_Description {
            get {
                return ResourceManager.GetString("PageArrangementShowDeleteButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PageArrangementShowPageNumber ähnelt.
        /// </summary>
        internal static string PageArrangementShowPageNumber {
            get {
                return ResourceManager.GetString("PageArrangementShowPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If true, each item of the page arrangement functionality will show it&apos;s page number. ähnelt.
        /// </summary>
        internal static string PageArrangementShowPageNumber_Description {
            get {
                return ResourceManager.GetString("PageArrangementShowPageNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment State ähnelt.
        /// </summary>
        internal static string paymentState_hint {
            get {
                return ResourceManager.GetString("paymentState_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment State ähnelt.
        /// </summary>
        internal static string paymentState_hint1 {
            get {
                return ResourceManager.GetString("paymentState_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone ähnelt.
        /// </summary>
        internal static string phone_hint {
            get {
                return ResourceManager.GetString("phone_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone ähnelt.
        /// </summary>
        internal static string phone_hint1 {
            get {
                return ResourceManager.GetString("phone_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PreCaptureFocus ähnelt.
        /// </summary>
        internal static string PreCaptureFocus {
            get {
                return ResourceManager.GetString("PreCaptureFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If true, the camera will run a focus action right before taking the image. This improves the quality of the scanned images, but depending on the device, image capture might take a little bit longer. This applies only to Android. ähnelt.
        /// </summary>
        internal static string PreCaptureFocus_Description {
            get {
                return ResourceManager.GetString("PreCaptureFocus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary ähnelt.
        /// </summary>
        internal static string primary {
            get {
                return ResourceManager.GetString("primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference ähnelt.
        /// </summary>
        internal static string reference_hint {
            get {
                return ResourceManager.GetString("reference_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference ähnelt.
        /// </summary>
        internal static string reference_hint1 {
            get {
                return ResourceManager.GetString("reference_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan buttons foreground ähnelt.
        /// </summary>
        internal static string scanButtonsForeground {
            get {
                return ResourceManager.GetString("scanButtonsForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan buttons layout background ähnelt.
        /// </summary>
        internal static string scanButtonsLayoutBackground {
            get {
                return ResourceManager.GetString("scanButtonsLayoutBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan polygon ähnelt.
        /// </summary>
        internal static string scanPolygon {
            get {
                return ResourceManager.GetString("scanPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan settings ähnelt.
        /// </summary>
        internal static string scanSettings {
            get {
                return ResourceManager.GetString("scanSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan single pages ähnelt.
        /// </summary>
        internal static string scanSinglePages {
            get {
                return ResourceManager.GetString("scanSinglePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secondary ähnelt.
        /// </summary>
        internal static string secondary {
            get {
                return ResourceManager.GetString("secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure color, scanner and editing of the SDK ähnelt.
        /// </summary>
        internal static string settingsDESC {
            get {
                return ResourceManager.GetString("settingsDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show delete button in page arrangement ähnelt.
        /// </summary>
        internal static string showDeleteButton {
            get {
                return ResourceManager.GetString("showDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show page arrangement option ähnelt.
        /// </summary>
        internal static string showPageArrangement {
            get {
                return ResourceManager.GetString("showPageArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show page cropping option ähnelt.
        /// </summary>
        internal static string showPageCropping {
            get {
                return ResourceManager.GetString("showPageCropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show page filter option ähnelt.
        /// </summary>
        internal static string showPageFilter {
            get {
                return ResourceManager.GetString("showPageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show page number in page arrangement ähnelt.
        /// </summary>
        internal static string showPageNumber {
            get {
                return ResourceManager.GetString("showPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show page rotation option ähnelt.
        /// </summary>
        internal static string showPageRotaion {
            get {
                return ResourceManager.GetString("showPageRotaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street ähnelt.
        /// </summary>
        internal static string street_hint {
            get {
                return ResourceManager.GetString("street_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street ähnelt.
        /// </summary>
        internal static string street_hint1 {
            get {
                return ResourceManager.GetString("street_hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Recognition (OCR) ähnelt.
        /// </summary>
        internal static string text_recognition {
            get {
                return ResourceManager.GetString("text recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Recognition (OCR) ähnelt.
        /// </summary>
        internal static string text_recognition1 {
            get {
                return ResourceManager.GetString("text recognition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run OCR on the previously scanned or imported (PDF or Image) document and get the recognized text. ähnelt.
        /// </summary>
        internal static string textRecognitionDesc {
            get {
                return ResourceManager.GetString("textRecognitionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run OCR on the previously scanned or imported (PDF or Image) document and get the recognized text. ähnelt.
        /// </summary>
        internal static string textRecognitionDesc1 {
            get {
                return ResourceManager.GetString("textRecognitionDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First, scan or import a document ähnelt.
        /// </summary>
        internal static string title_import_option {
            get {
                return ResourceManager.GetString("title_import_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First, scan or import a document ähnelt.
        /// </summary>
        internal static string title_import_option1 {
            get {
                return ResourceManager.GetString("title_import_option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top bar background ähnelt.
        /// </summary>
        internal static string topBarBackground {
            get {
                return ResourceManager.GetString("topBarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top bar foreground ähnelt.
        /// </summary>
        internal static string topBarForeground {
            get {
                return ResourceManager.GetString("topBarForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zipcode ähnelt.
        /// </summary>
        internal static string zipcode_hint {
            get {
                return ResourceManager.GetString("zipcode_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zipcode ähnelt.
        /// </summary>
        internal static string zipcode_hint1 {
            get {
                return ResourceManager.GetString("zipcode_hint1", resourceCulture);
            }
        }
    }
}
